title = "Abbey Farm Equestrian"
baseURL = "http://example.org/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"
publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/logo.jpg"
  description = "Abbey Farm Equestrian"
  background_color_class = "bg-black"
  recent_posts_number = 3
  ananke_socials = [
    { name = "facebook", link = "https://www.facebook.com/AbbeyFarmEquestrian/" },
    { name = "instagram", link = "https://www.instagram.com/abbey_farm_equestrian/" }
  ]
